name: soloquester
description: A modern fitness quest app inspired by anime solo leveling.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.3
  provider: ^6.0.5
  flutter_local_notifications: ^12.0.4
  animations: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
